ArndtLab/JuliaRegistry

- P/PopSimBase/Versions.toml
UUID: e60d1b08-a48f-4b5c-9e89-ad4b39d64fb4
Repo: git@github.com:ArndtLab/PopSimBase.jl.git
Tree: 7c7fc841c09e6fd467eca31bc6f91ab9a3746b31
> New version: PopSimBase v0.1.3

- A/ArndtLabJuliaRegistryTools/Versions.toml
Tree: eb2ba482dfcaf40e2125be6acf224acca0e6dcbb
> New version: ArndtLabJuliaRegistryTools v0.2.3

- P/PopSimIBX/Versions.toml
Repo: git@github.com:ArndtLab/PopSimIBX.jl.git
Tree: 6c7d2964277b1fc2be49d4218b9b086436223368
> New version: PopSimIBX v0.2.1

- A/ArndtLabJuliaRegistryTools/Versions.toml
Tree: 1af1701d17572cb3bf43b1232dc9631dfcc81711
> New version: ArndtLabJuliaRegistryTools v0.2.4

- P/PopSimForwardSim/Versions.toml
UUID: 0ec1a278-0482-4ecb-ba29-5ed973b8a48d
Repo: git@github.com:ArndtLab/PopSimForwardSim.jl.git
Tree: 5727aba0cc700730354ad6da5662e86deeb08c92
> New version: PopSimForwardSim v0.1.2

- A/ArndtLabJuliaRegistryTools/Versions.toml
Tree: 0cee557a091c59017d80e1d0e6722ff59bb35292
> New version: ArndtLabJuliaRegistryTools v0.2.5

- G/GnomADfilter/Versions.toml
UUID: 2104654b-de67-4eac-a5ee-be74140a16d3
Repo: git@github.com:ArndtLab/GnomADfilter.jl.git
Tree: ce7128ed513663289edfe15524bfa99d352854b2
> New version: GnomADfilter v0.1.3

- P/PopSimIBX/Compat.toml
- P/PopSimIBX/Versions.toml
Repo: git@github.com:ArndtLab/PopSimIBX.jl.git
Tree: 14db63245b9ba8be20f32de9b754f4c34bf33e83
> New version: PopSimIBX v0.2.2

- D/DemoInfer/Versions.toml
Tree: 5a5e123e179901efce85e0d89d24792f51d96fbc
> New version: DemoInfer v0.2.1

- D/DemoInfer/Versions.toml
Tree: 419e66c2d305dc19ac171862515f2a249a952025
> New version: DemoInfer v0.3.0

- D/DemoInfer/Versions.toml
Tree: 0bc143d9671093d1f331fbfb93eaeca0481c2ccd
> New version: DemoInfer v0.3.1

- G/GenomicCoordinates/Versions.toml
UUID: ba2eccb5-91b3-48f8-94f3-77bebdceebef
Repo: https://github.com/ArndtLab/GenomicCoordinates.jl.git
Tree: 3cc2b954205e78286d1990fb3a87ee8ea984a853
> New version: GenomicCoordinates v0.1.1

- G/GenomicCoordinates/Versions.toml
UUID: ba2eccb5-91b3-48f8-94f3-77bebdceebef
Repo: https://github.com/ArndtLab/GenomicCoordinates.jl.git
Tree: 22bc3bba5c6514a84a84cfdaa603642b10b4d770
> New version: GenomicCoordinates v0.1.2

- P/PopSimBase/Versions.toml
UUID: e60d1b08-a48f-4b5c-9e89-ad4b39d64fb4
Repo: https://github.com/ArndtLab/PopSimBase.jl.git
Tree: 81c1f5395e48d67983eb579d5c5ce63ed3d28be0
> New version: PopSimBase v0.2.1

- D/DemoInfer/Versions.toml
Tree: aee19fa53abd148ea4a00bf3f961065ea860bd5d
> New version: DemoInfer v0.3.3

- P/PopSimForwardSim/Versions.toml
UUID: 0ec1a278-0482-4ecb-ba29-5ed973b8a48d
Repo: git@github.com:ArndtLab/PopSimForwardSim.jl.git
Tree: ae4a4049fa65c8b6519a967c9643681d02ff6c46
> New version: PopSimForwardSim v0.1.5

- D/DemoInfer/Versions.toml
Tree: e089eac8dc01c587c1bf8bb6b4c955c8f344d857
> New version: DemoInfer v0.3.4

- D/DemoInfer/Versions.toml
Tree: 66a4fe41210fec2c3574afe3ace2681c7056bfa0
> New version: DemoInfer v0.4.0

- N/NotebookHelper/Deps.toml
- N/NotebookHelper/Package.toml
- N/NotebookHelper/Versions.toml
- Registry.toml
UUID: b0dc253a-7593-4df9-8537-7a9abf73c7af
Repo: git@github.molgen.mpg.de:ArndtLab/NotebookHelper.jl.git
Tree: 62942f3fdb2feb82db4ae1ca33867e0aeb0bdb11
> New package: NotebookHelper v0.1.4

- M/MariuxUtils/Versions.toml
UUID: be701e70-f25e-4246-ad85-09b5c637c424
Repo: git@github.molgen.mpg.de:ArndtLab/MariuxUtils.jl.git
Tree: e8ca3ca2141488e9f1b3e5bb4d25165d243a2a92
> New version: MariuxUtils v0.2.5

- N/NotebookHelper/Versions.toml
UUID: b0dc253a-7593-4df9-8537-7a9abf73c7af
Repo: git@github.molgen.mpg.de:ArndtLab/NotebookHelper.jl.git
Tree: 1a88f67353c69db62f8b157112b9c68f74377c74
> New version: NotebookHelper v0.1.5

- C/Cached/Versions.toml
UUID: 43ffbea4-38f1-43a5-9bfb-671206d3a474
Repo: git@github.molgen.mpg.de:ArndtLab/Cached.jl.git
Tree: aa8aa82743c390fcd532ea999dca3462eeea67aa
> New version: Cached v0.3.7

- P/PopSimIBX/Versions.toml
Tree: 9bd7263e8dcf02cff91d8e0cab7beef9a24e00a5
> New version: PopSimIBX v0.3.0

- P/PopSimIBX/Versions.toml
Tree: 644f33f44769895ae894cf91367f434f4d99d240
> New version: PopSimIBX v0.3.2

- A/ArndtLabJuliaRegistryTools/Versions.toml
Tree: b6423eb39a55cfe69d978f8d386c6ad30dda6171
> New version: ArndtLabJuliaRegistryTools v0.2.6

- A/ArndtLabJuliaRegistryTools/Versions.toml
Tree: 1d8b1bf38beafbd15b241cc7859ac5c182c384ee
> New version: ArndtLabJuliaRegistryTools v0.2.7

- A/ArndtLabJuliaRegistryTools/Versions.toml
Tree: 4b8ba415828d9d0b29ee96eab1e447e048535a66
> New version: ArndtLabJuliaRegistryTools v0.2.9

- C/Cached/Compat.toml
- C/Cached/Versions.toml
UUID: 43ffbea4-38f1-43a5-9bfb-671206d3a474
Repo: https://github.com/ArndtLab/Cached.jl.git
Tree: cbf20787997623a3b9cc044260aeb7faba238cec
> New version: Cached v0.4.0

- C/Cached/Versions.toml
UUID: 43ffbea4-38f1-43a5-9bfb-671206d3a474
Repo: https://github.com/ArndtLab/Cached.jl.git
Tree: 3e6c8438a06c951ba24fc4e9f0efa705f0b59190
> New version: Cached v0.4.1

- P/PopSimBase/Versions.toml
UUID: e60d1b08-a48f-4b5c-9e89-ad4b39d64fb4
Repo: https://github.com/ArndtLab/PopSimBase.jl.git
Tree: 4d80f4e065215c238743ca78839551838c16c7fb
> New version: PopSimBase v0.2.2

- P/PopSimIBX/Versions.toml
Tree: 8f4bd95eb5629da1f0bed69e8ada0c7df74d450e
> New version: PopSimIBX v0.3.3

- P/PopSimForwardSim/Versions.toml
UUID: 0ec1a278-0482-4ecb-ba29-5ed973b8a48d
Repo: git@github.com:ArndtLab/PopSimForwardSim.jl.git
Tree: 673f37b28204613d382365634e4d3eb605aa62f2
> New version: PopSimForwardSim v0.1.7

- C/Cached/Versions.toml
UUID: 43ffbea4-38f1-43a5-9bfb-671206d3a474
Repo: https://github.com/ArndtLab/Cached.jl.git
Tree: e49284bb6999db8659becd5ae94b7027542af9f6
> New version: Cached v0.5.0

- P/PopSimIBX/Versions.toml
Tree: e368ba40183d5ee8c09afc8a3e76e278587407b0
> New version: PopSimIBX v0.4.0

- M/MLDs/Versions.toml
UUID: cac4bed1-6c8c-4dbe-be0d-c63a427c1233
Repo: https://github.com/ArndtLab/MLDs.jl.git
Tree: aece53717b29b88d51554a4e8f853b7d92b3e1de
> New version: MLDs v0.1.3

- D/DemoInfer/Versions.toml
Tree: 3e87639398be38a026e132eb76a653e45bdac082
> New version: DemoInfer v0.6.0

- P/PopSimIBX/Versions.toml
Tree: 96be8eb807097d74a21e2ad645c23eb168adcc21
> New version: PopSimIBX v0.4.1

- D/DemoInfer/Versions.toml
Tree: a0feec7aaf05821319007b2400ce0a2abc0f91ce
> New version: DemoInfer v0.7.2

- D/DemoInfer/Versions.toml
Tree: a299598038992c44dd406b219058adc8d7dbdf86
> New version: DemoInfer v0.8.0

- P/PopSim/Versions.toml
UUID: 607e1499-206c-4cd0-b740-8138de4d5c8a
Repo: https://github.com/ArndtLab/APop.jl.git
Tree: e4254aac7d42f822d4d90c6187b6e4504223ad43
> New version: PopSim v0.1.1

- P/PopSim/Versions.toml
UUID: 607e1499-206c-4cd0-b740-8138de4d5c8a
Repo: https://github.com/ArndtLab/PopSim.jl.git
Tree: 91b6f3acfcffcd93fb55ccf5811d5346500a27de
> New version: PopSim v0.1.4

- P/PopSim/Versions.toml
UUID: 607e1499-206c-4cd0-b740-8138de4d5c8a
Repo: https://github.com/ArndtLab/PopSim.jl.git
Tree: 75e932fd98fffa0f4f0ba64ab9793c943dacee19
> New version: PopSim v0.2.0
